ratio: 1
buffer_size: 50
original_buffer_size: 5
objects_names: coco.names
zones:
  - name: Casa
    path: http://localhost:5000/processframe

  - name: Politecnico
    path: http://130.192.225.63:32251/processframe
