
apiVersion: v1
kind: ConfigMap
metadata:
  name: cv-middle-config
data:
  config.yml: |
    ratio: 1
    buffer_size: 1
    original_buffer_size: 5
    objects_names: coco.names
    zones:
      - name: "Edge"
        path: http://130.192.225.73:31532/processframe

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-middle-deployment
  labels:
    app.kubernetes.io/name: cv-yolo-middle
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cv-yolo-middle
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cv-yolo-middle
    spec:
      containers:
      - name: yolo-middle-pod 
        imagePullPolicy: Always
        image: mlvc/front
        name: yolo-middle
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cvconfig
        ports:
        - containerPort: 5005
        resources:
          requests:
            memory: "2048Mi"
            cpu: 2
          limits:
            memory: "2048Mi"
            cpu: 2
      volumes:
        - name: config-volume
          configMap:
            name: cv-middle-config 

---

apiVersion: v1
kind: Service
metadata:
  name: yolo-middle-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: cv-yolo-middle
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005